# Fuente
font_family JetBrainsMono Nerd Font 
bold_font JetBrainsMono Nerd Font 
italic_font JetBrainsMono Nerd Font 
bold_italic_font JetBrainsMono Nerd Font
font_size        10.5

symbol_map U+E000-U+F8FF Symbols Nerd Font Mono
disable_ligatures never
enable_hyperlinks yes


foreground   #BBD6CC
background   #0E1A1A

cursor       #94E2D5
selection_foreground #0E1A1A
selection_background #D2F3EE

color0  #1F2A2A   
color1  #D97B7B   
color2  #A0D6B4   
color3  #EADCA6   
color4  #87CACC   
color5  #D4A6D7   
color6  #94E2D5   
color7  #E5F3EF   

color8  #344040   
color9  #F29B9B   
color10 #BEEFD3   
color11 #FFF5BF   
color12 #A4E2E2   
color13 #F1C6F3  
color14 #BBFFF3   
color15 #FFFFFF   

padding_width 10
cursor_blink_interval 0.6
scrollback_lines 10000
confirm_os_window_close 0
shell_integration enabled

cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05
cursor_shape block
cursor_blink true
