general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 0, 0, 1, 1
    animation = fadeIn, 1, 4, linear
    animation = fadeOut, 1, 4, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/jose/Imágenes/Wallpapers/wallhaven-chido.jpg
    blur_passes = 1
    blur_size = 5
}

input-field {
    monitor =
    size = 260, 55
    outline_thickness = 3
    rounding = 0

    inner_color = rgba(14, 26, 26, 0.8)
    outer_color = rgba(148, 226, 213, 1.0)
    check_color = rgba(187, 255, 243, 1.0)
    fail_color = rgba(217, 123, 123, 1.0)

    font_color = rgb(187, 214, 204)
    fade_on_empty = false

    font_family = JetBrainsMono Nerd Font
    placeholder_text = contraseña
    fail_text = error
    dots_text_format = *
    dots_size = 0.4
    dots_spacing = 0.2

    position = 0, -180
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 80
    font_family = JetBrainsMono Nerd Font
    font_color = rgb(187, 214, 204)
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A"
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    font_color = rgb(160, 214, 180)
    position = 0, 70
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%d %b"
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    font_color = rgb(160, 214, 180)
    position = 0, 40
    halign = center
    valign = center
}
